/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import static org.hamcrest.CoreMatchers.*;

import math.Vector2D;

public class AppTest {
    @Test public void mostDifficultTest() {
        assertThat("The universe is sane", 1+1, is(2));
    }

    @Test public void ensureVectorsAdd() {
        Vector2D vector = new Vector2D(10, -2);
        vector.add(new Vector2D(1, 5));
        vector.add(-1, -4);
        assertThat("Vector addition works", vector.x, is(10.0));
        assertThat("Vector addition works", vector.y, is(-1.0));
    }

    @Test public void vectorAngles() {
        Vector2D vector1 = new Vector2D(3, 3);
        assertEquals("The angle is correct (quadrant 1)", vector1.getAngle(), Math.PI / 4, 1e-5);
        Vector2D vector2 = new Vector2D(10, -10 * Math.sqrt(3));
        assertEquals("Angle in quadrant 4", vector2.getAngle(), -Math.PI / 3, 1e-5);
        Vector2D vector3 = new Vector2D(-5, 0);
        assertEquals("180 degree vector", vector3.getAngle(), -Math.PI, 1e-5);
    }
}
